### ISSUE TITLE
Doesn't work correctly with Catalina wine32on64?

### ISSUE THREAD

**Issue by AgentRG** [aljen/swtor_fix#10]
I have been taking care of a guide on how to run the game on macOS systems. Recently I saw a huge increase in people asking me how to run it on Catalina, so I ventured into the unknown and updated to Catalina.

With wine32on64 in place and boot args set to allow 32 bit, it looks like the pre-swtor_fix issue came back even though the fix did launch correctly. Ship sounds playing in the background but not launching. Wondering if you might give some tips on what might be going on. Screenshot attached. 
<img width="1440" alt="Screen Shot 2020-04-05 at 4 24 17 PM" src="https://user-images.githubusercontent.com/23729455/78512620-1e29b300-775b-11ea-9192-6e128550a487.png">

**Comment by AgentRG** [comment]
This is the error generated in the log:
`wine: Unhandled page fault on write access to 0x7ffe0010 at address 0x1007:0x0040158c (thread 0086)`

**Comment by AgentRG** [comment]
@aljen Do you by any chance still work on this project? Another person and I were trying to make the fix work on Catalina but got nowhere so far. Different settings kept giving the same error I posted before.

**Comment by aljen** [comment]
Hey, sorry I have no time lately :(

Tbh, the last time I was using apple products, it was ~15-20 years ago, so I don't know anything about the state of wine/swtor on it,etc.
I'm not playing swtor anymore too - don't have time, so I'm not working anymore on this project :/

**Comment by AgentRG** [comment]
@aljen What a shame. Okay, can you by any chance throw a random guess on what might be happening? Anything will help. Your tiny fix was of great help to the Mac SWTOR community for last decade.

**Comment by aljen** [comment]
@AgentRG 
Hey, sorry,
to be honest, I don't know, from observed behavior and that sounds are playing but it is stuck in the loading screen, I'd say that OSX won't allow modifying other process memory, maybe security reasons? maybe you can add exceptions?
But I would go into this direction :/
I'm just guessing, sorry :(

**Comment by AgentRG** [comment]
@aljen Yea. Apple added several user security restrictions with macOS Catalina. I guess one of them is the ability to edit process memory. StackOverflow is being useless as usual.
